CREATE TABLE Publishers (Publisher_Id CHAR(5), Name CHAR(30), URL CHAR(80))
INSERT INTO Publishers VALUES ('01262', 'Academic Press', 'www.apnet.com/')
INSERT INTO Publishers VALUES ('18835', 'Coriolis', 'www.coriolis.com/')
INSERT INTO Publishers VALUES ('18879', 'Franklin, Beedle & Associates', 'www.fbeedle.com/')
INSERT INTO Publishers VALUES ('15688', 'IDG Books', 'www.idgbooks.com/')
INSERT INTO Publishers VALUES ('05345', 'Integrated Media Group', 'www.thomson.com/rcenters/img/img.html')
INSERT INTO Publishers VALUES ('00791', 'McGraw-Hill', 'www.mcgraw-hill.com/')
INSERT INTO Publishers VALUES ('15561', 'Microsoft Press', 'www.microsoft.com/mspress/')
INSERT INTO Publishers VALUES ('15660', 'Netscape Press', 'www.netscapepress.com/')
INSERT INTO Publishers VALUES ('15620', 'New Riders', 'www.mcp.com/newriders/')
INSERT INTO Publishers VALUES ('15659', 'O''Reilly', 'www.ora.com/')
INSERT INTO Publishers VALUES ('00788', 'Osborne/McGraw-Hill', 'www.osborne.com')
INSERT INTO Publishers VALUES ('00218', 'Peachpit Press', 'www.peachpit.com/')
INSERT INTO Publishers VALUES ('01356', 'Prentice Hall', 'www.prenhall.com/')
INSERT INTO Publishers VALUES ('07897', 'Que', 'www.mcp.com/que/')
INSERT INTO Publishers VALUES ('15752', 'Sams.net', 'www.mcp.com/samsnet/')
INSERT INTO Publishers VALUES ('15716', 'Waite', 'www.waite.com/waite/')
INSERT INTO Publishers VALUES ('04711', 'Wiley', 'www.wiley.com/')
INSERT INTO Publishers VALUES ('15627', 'Ziff-Davis', 'www.mcp.com/zdpress/')
SELECT * FROM Publishers
